#!/usr/bin/env bash
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_311.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_150.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_097.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_188.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_066.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_063.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_313.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_006.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_382.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_561.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_071.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_248.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_393.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_041.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_053.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_038.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_057.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_290.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_584.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_110.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_301.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_045.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_178.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_077.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_119.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_085.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_030.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_120.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_069.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_036.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_061.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_398.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_089.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_277.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_091.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_185.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_112.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_092.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_155.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_559.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_067.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_087.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_077.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_362.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_109.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_108.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_402.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_080.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_076.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_043.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_591.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_384.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_045.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_284.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_072.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_062.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_320.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_249.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_064.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_392.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_060.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_281.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_035.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_549.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_126.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_156.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_570.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_322.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_034.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_033.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_233.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_282.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_070.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_355.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_092.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_087.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_363.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_119.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_059.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_590.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_314.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_276.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_173.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_172.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_218.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_046.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_315.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_018.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_173.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_153.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_124.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_068.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_063.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_099.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_089.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_187.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_200.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_050.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_077.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_059.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_407.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_033.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_068.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_280.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_283.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_091.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_090.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_110.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_211.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_102.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_325.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_573.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_103.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_050.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_123.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_182.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_121.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_621.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_114.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_121.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_082.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_096.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_062.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_073.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_059.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_013.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_073.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_050.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_103.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_110.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_036.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_073.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_128.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_275.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_018.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_093.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_015.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_201.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_014.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_147.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_161.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_063.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_287.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_038.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_059.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_321.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_121.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_603.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_052.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_295.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_595.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_303.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_118.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_337.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_239.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_006.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_582.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_293.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_046.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_041.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_015.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_055.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_234.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_113.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_109.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_102.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_038.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_021.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_074.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_617.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_021.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_030.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_317.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_093.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_131.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_085.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_102.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_596.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_162.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_162.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_349.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_236.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_223.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_053.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_255.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_310.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_567.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_021.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_110.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_047.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_018.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_083.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_061.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_064.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_063t.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_165.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_080.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_042.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_066.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_018.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_326.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_243.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_081.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_536.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_250.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_245.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_117.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_254.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_613.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_107.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_002.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_142.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_051.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_079.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/PRO_001.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_189.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_104.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_170.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_107.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_078.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_104.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_619.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_274.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_113.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_114.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_124.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_082.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_111.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_108.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_105.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_076.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_537.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_610.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_131.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_132.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_141.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_564.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_174.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_207.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_129.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_044.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_053.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_301.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS1_069.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_115.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_047.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_248.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_015.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_179.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_106.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_042.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_129.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_319.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_094.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_001.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_001.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_032.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_565.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_002.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_544.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_055.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/tt_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_100.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_084.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_113.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_051.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_086.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_198.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_114.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_101.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_571.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_079.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_002.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_251.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_292.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_073.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_611.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_093.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_283.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_120.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_037.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_121.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_226.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_604.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_095.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_133.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_049.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_080.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_117.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_112.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_308.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_081.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_188.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_043.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_098.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_092.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_147.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_095.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS1_042.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_411.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_039.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_122.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_118.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_508.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_414.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_152.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_032.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_038.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_088.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_399.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_209.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_094.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_371.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_558.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_556.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_002.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_137.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_048.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_062.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_120.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_316.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_105.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_246.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_104.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_040.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_318.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_624.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_089.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS1_112.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS1_130.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_365.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_334.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_070.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_046.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_360.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_084.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_289.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_295.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_092.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_125.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_614.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_089.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_006.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_597.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_045.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_045.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_249.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_216.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_181.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_105.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS1_129.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_607.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_169.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_056.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_232.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_203.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_141.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_125.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_094.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_072.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_051.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_106.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_132.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_166.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_013.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_074.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_539.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_543.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_014.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_046.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_065.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_058.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_612.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_188.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_041.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_142.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_099.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_119.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_084.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_241.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_354.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_116.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_106.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_091.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_238.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_259.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_335.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_001.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_341.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_097.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_037.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_030.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_061.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_096.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_323.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_162.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_100.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_071.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_082.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_082.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_090.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_118.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_067.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_085.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_021.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_220.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_035.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_563.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_055.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_575.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_616.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_155.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_048.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_626.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_112.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_037.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_117.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_014.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_328.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_034.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_078.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_006.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_116.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_048.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_103.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_320.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_111.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_233.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS1_113.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_085.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_345.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_109.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_202.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_294.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_533.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_018.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_112.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_088.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_396.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_620.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_302.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_408.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_105.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_050.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_090.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_122.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_044.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_183.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_076.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_168.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_509.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_506.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOEA10_3.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_507.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_006.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_061.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_079.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_312.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_133.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_038.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_557.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_338.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_161.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_030.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_042.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_138.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_127.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_593.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_130.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_103.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_235.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_164.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_015.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_560.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_119.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_065.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_197.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_088.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_054.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_062.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_061.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_562.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_066.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_522.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_133.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_096.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_105.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_076.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_101.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_313.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_034.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_323.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_241.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_316.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_013.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_094.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_160.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_036.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_056.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_145.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_583.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_309.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_350.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_145.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_064.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_279.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_060.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_044.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_013.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_412.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_298.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_229.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_122.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_222.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_104.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_149.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_115.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_161.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_196.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_213.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_108.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_113.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_031.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_136.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_111.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_116.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_029.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_118.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_379.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_015.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_120.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_045.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_134.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_047.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_086.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_070.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_581.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_039.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_578.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_534.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_271.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_101.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_531.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_055.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_586.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_130.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_074.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_057.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_080.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_221.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_179.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_317.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_087.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_005.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_057.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_334.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_176.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_622.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_100.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_234.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_072.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_291.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_014.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_303.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_625.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_144.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_032.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_081.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_606.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_410.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_405.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_058.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_053.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_123.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_335.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_075.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_278.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_098.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_086.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_332.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_095.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_034.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_040.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_151.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_100.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_127.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_075.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_309.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_076.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_339.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_070.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_391.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_554.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_114.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_609.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_002.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_340.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_001.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_123.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_608.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_158.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_308.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_146.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_267.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_069.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_256.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_008.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/tt_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_048.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_044.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_221.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_116.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_077.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_327.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_057.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_014.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_041.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_273.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_007.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_173.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_237.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_087.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_310.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_067.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_171.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_206.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_247.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_150.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_222.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_131.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_306.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_315.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_086.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_058.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_032.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_366.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_093.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_390.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_623.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_151.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_033.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_577.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_002.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_300.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_054.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_128.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_073.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_339.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_021.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_049.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_175.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_102.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_083.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_021.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_383.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_012.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_047.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_115.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_052.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_244.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_097.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_091.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_184.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_033.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_118.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_097.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/DS1_178.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_018.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_104.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_046.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_096.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_043.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_286.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_083.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_284.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_017.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_272.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_131.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_247.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_312.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_258.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_330.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_030.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_028.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_019.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_538.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_024.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_003.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_409.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_083.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_302.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_200.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_594.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_072.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_227.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_006.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_039.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_023.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_304.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_022.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_065.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_014.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_025.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/BRM_009.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_016.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_186.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_051.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_075.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_084.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_033.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_011.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_122.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/GVG_037.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_400.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_013.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_020.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_040.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_027.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_039.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_033.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_587.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_231.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_195.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/LOE_089.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_124.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_010.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_154.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_026.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/AT_116.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_080.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_042.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_134.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_169.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_004.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_049.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_572.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/OG_158.png
wget http://wow.zamimg.com/images/hearthstone/cards/enus/original/FP1_001.png
